### ISSUE TITLE
Nemesis AI should set bounties and have basic interactions

### ISSUE THREAD

**Issue by luttje** [luttje/gmod-experiment-redux#100]
For the first Epoch I'm hoping we can have the following features implemented:

The Nemesis AI can:
- [x] set bounties on players leading the leaderboards
- [ ] show messages on the monitors in the city (low priority)
- [x] speak Text-To-Speech (TTS) messages through the city
- [x] show message in chat besides only speaking TTS (for improved accessibility) f5f605ca4137d8746b4c248122ae4d2728f1adaf
- [ ] Implement task to remove bounty and prevent friends claiming bounties (read in the comment below)
- [ ] Implement bounty timeout, so the same player doesn't constantly get bounties every hour

## Additional notes
- **For what in-world reason does the AI set bounties?** 
I'm thinking that because the rebels oppose the AI, and because the rebels manage the leaderboards, it makes sense for the AI to want to thwart those helping the rebels.

- **How often does the Nemesis AI set bounties?** 
Every hour atm.

- **For how long does the bounty last?** 
30 minutes.

**Comment by luttje** [comment]
(enable audio) Here's a quick test of the TTS system:

https://github.com/luttje/gmod-experiment-redux/assets/2738114/b51b60d2-5f4e-45bf-8f53-7f2cf0fdc9dd

**Comment by luttje** [comment]
Another sneak peak of progress on the speech:

https://github.com/luttje/gmod-experiment-redux/assets/2738114/9d97d749-042a-4af1-a462-7951311a7fd5

Next up is the logic on when the AI speaks and when it sets bounties

**Comment by utaysi** [comment]
It could be nice to also print the text on the chat, or as subtitles. When it plays out suddenly without the players expecting, it might be hard to tell what was said by the AI.

**Comment by luttje** [comment]
You're exactly right! A message in chat seems like a nice easy way to implement this. Will add it to the list :)

**Comment by luttje** [comment]
I've implemented basic bounties, but see a lot of room for circumvention. For example when your friend gets a bounty on them, you simply log off, ask a friend to come online with you and then let them claim the bounty.

I've written up a game mechanic that I think discourages this pretty smartly. I don't see an obvious way to abuse it. I'd love to hear suggestions or comments if anyone sees any problems.

## Preventing friends claiming bounties
Obviously if a bounty is set on your mate, and you're next to them, you just claim it and share the prize. We should prevent this somehow, preferably with simple mechanics. For example: 'tracking who are friends, by keeping track of their distances to each other' is way too complicated. I've come up with the following simpler idea:

The target getting a bounty on their head is instructed to perform a specific task:
1. The AI quietly informs the target the 'Locker Rot Virus' is threatening to expose the items in one of their lockers.
2. They have to get X amount of their valuable items or bolts from a specific locker (e.g: at XCCR)
  _If they reject the task or disconnect their locker will drop those items and the city will be informed of it_
3. After grabbing the items they are told to which other locker they have to bring it (e.g: near the Train Station). That locker has the only anti-virus that can save their items.
4. The bounty is now announced to the city, whilst they're trying to run to the other side of the map holding their valuables.
   _This incentivizes their friends to help them out, rather than to claim the bounty for themselves._ 
   _Additionally the bounty bolts/items are not created from nothing, instead they come from the player with the bounty (not increasing the amount of wealth in the economy)_
5. When someone kills the target, the target drops 50% of their items/bolts. The rest is consumed by the 'Locker Rot Virus' 
   _This means the target's friends can't just help out by killing them, as it would result in a loss._ 
   _Additionally the total amount of wealth in the economy is reduced._
6. If the target survives and successfully makes it within range of the safe locker, the bounty is immediately lifted and they get to keep their items.

Some alternative ideas I had, which I dislike for their complexity and ease to abuse:
- Any characters nearby the target when the bounty is placed are disqualified from participating
- Have the bounty last multiple hours, even persisting through death. After the bounty expires, randomly select one of the characters that killed the target. Only they get the reward. This makes it harder to collude, because other players will also have a chance to kill the target.
