### ISSUE TITLE
Buggy doors

### ISSUE THREAD

**Issue by LOLHoboMan** [luttje/gmod-experiment-redux#111]
Opened the lockers in the nexus zombie infested area and the doors spun around and had effect where some of the locker doors were floating in the elevator.

Links to some photos:
 https://steamcommunity.com/sharedfiles/filedetails/?id=3261442184 
https://steamcommunity.com/sharedfiles/filedetails/?id=3261441285

**Comment by LOLHoboMan** [comment]
It's the room straight left from the short elevator that leads to nexus lobby underground

**Comment by luttje** [comment]
Thanks a bunch for reporting this! Will be fixed the next map update #96 :)
