### ISSUE TITLE
Monsters to loot

### ISSUE THREAD

**Issue by Nelaif** [luttje/gmod-experiment-redux#74]
Generators were the AFK earners. But there should be more. 
I saw that scrap pile video and that was good. Having like +/- 15 random items with which you can craft with or scrap for bolts / money.
So then I assume some places will have this scrap piles where people start building a base around or mark as territory.

Another eco influx could be monster farms. Every 25th minute there will be headcrabs raining down or some other infestation, depends on the map. With some mobs on the loose there will alwayse be some excitement in the streets and a reason to carry a knife.

Everybody gets warned that  the crabs are comimg. So those who want to go out to farm the mobs for loot can go. But it will also create an enviroment for bully muggings. Stalking other players which are hunting monsters. 

I dont really know other ways to generate an economy except if people had the skill to add modifications to weapons. This person could be hired to tweak weapons. Scams could happen and such, but this makes it all the better.

I think the way with skill learning that it could create very much scenarios of people working together (maybe all get murdered in the end)

**Comment by luttje** [comment]
Thanks for another great contribution.

Currently weapon attachments can be purchased in the Business tab (if you get the Gunsmith perk). We could consider moving that to a skill so you could craft them for another player.

You've mentioned crafting a couple times, I'm going to think about how that would work and how long it may take to implement.

**Comment by luttje** [comment]
Your idea for mobs spawning somewhere has found residence somewhere in my brain. I really like the idea of places where players can farm mobs for loot. That may find its way in before launch, since we could use some more things to do imo.

**Comment by luttje** [comment]
Took some time to figure out npc logic in Garry's Mod today. The basics for monsters + looting are there:

https://github.com/luttje/gmod-experiment-redux/assets/2738114/74cded3a-0048-4c1d-a33e-f73282de359e

Just gotta balance it and make monsters more challenging. Although monsters do a ton of damage, they're a bit easy to strafe around atm.

**Comment by Nelaif** [comment]
Great work!!! This is going to be nice!

**Comment by Nelaif** [comment]
Great work!!! This is going to be nice!
@luttje I believe that lower nexus is a good spot as a dungeon. The prison part. I would not take the whole nexus. Or partly, one day upper, one day lower. So in that case there will be some variaty. If you ever played Sons of the Forests, that would be nice monsters to have as an addon. But that might be complicated i think.

**Comment by luttje** [comment]
Got rid of the default zombie models in favor of something fitting with the lore:

https://github.com/luttje/gmod-experiment-redux/assets/2738114/e5595fb0-4e19-43ac-add2-81c59596d191

As you might be able to tell from the monsters standing into corners, they're AI is pretty broken atm. That's something I hope to fix after the beta.

**Comment by luttje** [comment]
## Task list

- [x] Add monsters with loot
- [ ] Spawn monsters from map (see #96)
- [ ] Automatically respawn monsters after a while
- [ ] Improve monster AI (it's a bad atm)
- [ ] Optimize monsters when nobody is around (e.g: slowing thinking, or disabling it entirely
