### ISSUE TITLE
Admins - Special Playable Character

### ISSUE THREAD

**Issue by Nelaif** [luttje/gmod-experiment-redux#76]
These come in pairs. 2 admins online in duty come together as antagonists. 

One could be a noble peacekeeper. 
The other is a notorious anarchist. 

They strive to make eachother's lives unpleasant. They will draw in bystanders (other players) to do their bidding. 

Petty rewards for roleplaying with the SPC will be granted to the players. 

Both SPC's will (in private, out of character) agree for a climax event where their pawns (the normal players) will be pit to fight eachother. All rewards of the conquests go to the players. 

The SPCs will not kill players. Maybe fight eachother. Preferably not. An SPC may get killed by players, but this must all be in the boundries of the plan and loot which we are giving in these events.

Both SPCs must be trusted to not abuse their status to create wealth for them or others beyond the evented scenario. Both SPCs have an obligation to controle eachothers via the logs.

If one SPC gets caught with malpractise, they both get demoted. 

Scenarios must be written beforehand. They must be approved by the server owner.

Cheers :)

**Comment by luttje** [comment]
Thanks a bunch for all your great contributions @Nelaif! Although I'll be closing this issue for the reasons explained above and to keep things organized here on GitHub.

I really do think it's a good idea for a community server or perhaps an automated version in the future.

Thanks again!
