### ISSUE TITLE
Generator Pick Up Penalty During Raids

### ISSUE THREAD

**Issue by utaysi** [luttje/gmod-experiment-redux#80]
Generator upgrades are worth a lot if fully upgraded. They are lost once destroyed but if you pick it up they are safe. People can pick up their generator while getting raided to avoid losing their upgrades. 

- There could be a mechanic added to deny you picking it up in your inventory while getting raided. 
- Or after you pick it up you get a timer debuff (5-10 mins), if you die it will count as if it was destroyed.

**Comment by luttje** [comment]
Great points and great suggestions to counter it, much appreciated!

I think easiest to implement would be:
- The debuff you mentioned (got any ideas for fun names?)
- A delay before picking up the generator (say that you have to look at it for 30s uninterrupted)

Note to self: a related issue will be that a user can disconnect to avoid getting their generator destroyed (which will immediately remove their generator).

**Comment by luttje** [comment]
I've added a 20 second grace period so players can pick up the generator and place it differently without having to wait 30 seconds to pick it up. After that it takes 30s to pick up.

Closing this for now, since it's somewhat solved the original issue imo
